name: Hello Actions

on:
  push:
    branches: feature
  pull_request:
    types: [closed]

env:
  name: fmunirdev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: fmunir
    steps:
    - name: Run a one-line script
      run: echo Hello, $name!

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hi, $name.
