name: Hello Actions

on:
  push:
    branches: feature
  pull_request:
    types: [closed]

env:
  name: fmunirdev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: fahad
    steps:
    - name: Run a one-line script
      run: echo Hello, $name!

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hi, $name.
  
  weather:
    name: Fetch weather data
    runs-on: ubuntu-latest
    env:
      locationKey: 260622
      lang: en-us
      details: false
      apiKey: ${{ secrets.ACCUWEATHER }}
    steps:
      - name: Current Weather in Lahore
        run: curl -s --url http://dataservice.accuweather.com/currentconditions/v1/$locationKey?apikey=$apiKey&language=$lang&details=$details
